
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 40.1.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
