apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alucard-postgres
  namespace: alucard-postgres
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "11.9.10"
      sourceRef:
        kind: HelmRepository
        name: alucard-postgres
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: alucard-postgres-values
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
