apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-redis
  namespace: authentik-redis
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "17.3.5"
      sourceRef:
        kind: HelmRepository
        name: authentik-redis
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: authentik-redis-values
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
