apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: gitea-values
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
