---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/prometheus-community/helm-charts.git
