apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-auth
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
