namespace: external-secrets
configMapGenerator:
  - name: external-secrets-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - namespace.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - helm-release.yaml

patches:
  - target:
      kind: ClusterRole
      name: eso-external-secrets-controller
    patch: |-
      - op: add
        path: /rules/0
        value:
          apiGroups:
            - authentication.k8s.io
            - authorization.k8s.io
          resources:
            - tokenreviews
            - subjectaccessreviews
          verbs:
            - create
            - delete
            - get
            - list
            - update
            - watch
      - op: add
        path: /rules/0
        value:
          apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
          verbs:
            - create
            - delete
            - get
            - list
            - update
            - watch