namespace: external-secrets
configMapGenerator:
  - name: external-secrets-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - namespace.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - helm-release.yaml
  - sa-tokens.yaml
  - ./crds
