apiVersion: v1
kind: Secret
metadata:
  name: eso-external-secrets-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: eso-external-secrets
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-cert-controller-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: external-secrets-cert-controller
type: kubernetes.io/service-account-token
