apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: external-secrets
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: test
  dataFrom:
    - extract:
        key: kv/development/test
