replicaCount: 1
image:
  repository: spencerrung/eso
  tag: "v0.6.0"
installCRDs: true
crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
concurrent: 2
serviceAccount:
  create: true
rbac:
  # -- Specifies whether role and rolebinding resources should be created.
  create: true
serviceMonitor:
  enabled: false
webhook:
  create: true
  image:
    repository: spencerrung/eso
    tag: "v0.6.0"
  port: 10250
  rbac:
    create: true
  serviceAccount:
    create: true
certController:
  create: true
  image:
    repository: spencerrung/eso
    tag: "v0.6.0"
  rbac:
    create: true
  serviceAccount:
    create: true
