replicaCount: 1
image:
  repository: ghcr.io/external-secrets/external-secrets
  tag: "v0.6.0-rc1.33.gad4bd386@sha256:e3e7b3b17b052c4767266211503aa9b8fe158e12479bdacf002eac6be71b1989"
installCRDs: true
crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
concurrent: 2
serviceAccount:
  create: true
rbac:
  # -- Specifies whether role and rolebinding resources should be created.
  create: true
serviceMonitor:
  enabled: false
webhook:
  create: true
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: "v0.6.0-rc1.33.gad4bd386@sha256:e3e7b3b17b052c4767266211503aa9b8fe158e12479bdacf002eac6be71b1989"
  port: 10250
  rbac:
    create: true
  serviceAccount:
    create: true
certController:
  create: true
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: "v0.6.0-rc1.33.gad4bd386@sha256:e3e7b3b17b052c4767266211503aa9b8fe158e12479bdacf002eac6be71b1989"
  rbac:
    create: true
  serviceAccount:
    create: true
