apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: "2022.8.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
