namespace: authentik
configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - namespace.yaml
  - helm-release.yaml
