# -- Server replicas
replicas: 3
worker:
  replicas: 3
authentik:
  error_reporting:
    enabled: true
envFrom:
  - secretRef:
      name: authentik
ingress:
  enabled: false
prometheus:
  serviceMonitor:
    create: true
