apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentik-redis
  namespace: flux-system
spec:
  interval: 5m
  path: ./authentik-redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: authentik-redis
