apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alucard-postgres
  namespace: flux-system
spec:
  interval: 5m
  path: ./alucard-postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: alucard-postgres
