---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: vault
