apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: ">=0.21.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: vault-values
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
