apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  interval: 5m0s
  path: "./external-secrets/crds/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets