apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets