apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/spencerrung/k3s-flux.git
