apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: master
  secretRef:
    name: gitea
  url: ssh://git@github.com/spencerrung/k3s-flux.git
