apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 10m
  path: ./tekton
  prune: true
  sourceRef:
    kind: GitRepository
    name: tekton
