apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: master
  secretRef:
    name: tekton
  url: ssh://git@github.com/spencerrung/k3s-flux.git
